### ISSUE TITLE
UAT feedback

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#232]
Will be so good to get this over the line! Woohoo. The website is big, bold, and fresh. A string of comments, don't be disheartened, just things I noticed before I ran out of time and had to go get lunch!

On my laptop (Dell XPS 13"):

- [x] #236
- [ ] Text truncated ("We're based in Wellington, New") (Zealand is below the fold)
- [ ] The tagging of publications (the by subject filter) is very out of date. They either need manual review, or else, dare I say it, some data science. Maybe the simplest is to remove these for now.
- [x] #239
- [ ] Yvan is looking at a better way of finding similar stories so that "You might also like these stories " is more meaningful
- [x] I find it weird how in the top menus the text in the drop down is larger than the text in the menu itself. Also the text in the dropdown feels crushed to me.
- [x] The "Staff contact details" link isnt quite right when you are already on the people page, it doesnt take you back to the top
- [x] Can we replace the google maps link with this one https://goo.gl/maps/XHdWy5kXSap3VdNS8 - this takes the visitor to our Google Maps business page, rather than the street address
- [x] On the front page, caps on "Find out more"
- [x] On the front page, the heading is "Latest news" but not all the tiles are news. Can we do without this heading. It looks a bit orphaned on the page, and the tiles have there own headings anyway?
- [x] Also the stories aren't the latest. Would be good if they could be auto-updated during the build so that the front page stayed fresh. Probably needs some Hakyll work.
- [x] The people page has a "Meet the team" heading, while the projects, work, and news pages don't. Do we need this? Feels orphaned to me, and  I don't think it adds to the page (Who we are and teh down arrow are already strong signage).
- [ ] A custom CSL for the publications would be good. I would remove the "retrieved from" part from this tile (it is a URL inside another URL and looks messy here), put the authors on one line, and the other publication info on a following line (the title and year don't need to be repeated).

On my phone:
- [x] The dragonfly data science logo is very small, and I cant really read it. We kind of need that to be clearly legible so people know they are here.
- [x] #237

**Comment by edwardabraham** [comment]
Actually, the problem with the news search is that it shows one less tile than it indicates it has results for!

**Comment by simonwinter** [comment]
>  On the front page, the heading is "Latest news" but not all the tiles are news. Can we do without this heading. It looks a bit orphaned on the page, and the tiles have there own headings anyway?
> Also the stories aren't the latest. Would be good if they could be auto-updated during the build so that the front page stayed fresh. Probably needs some Hakyll work.

Agree that the title is incorrect. The idea here is more that we promote certain stories rather than simply the latest news. We could certainly automate it, but it reduces our control of what we want to promote.

**Comment by edwardabraham** [comment]
Makes sense. So, change the heading and see if we can manage to update the
home page now and then?

**Comment by pepzuijderwijk** [comment]
With the new homepage approach the idea was to only have news stories so it would just show the 4 latest, just as in the news section itself.

**Comment by pepzuijderwijk** [comment]
For reasons mentioned above!

**Comment by pepzuijderwijk** [comment]
Hey @edwardabraham Here are my comments on the design related ones. The logic of the system I'll leave with you & simon.
1. The "Staff contact details" link isnt quite right when you are already on the people page, it doesnt take you back to the top
Do you mean from the footer? I would just remove that link from the footer. People know where to find the individuals.

2. I find it weird how in the top menus the text in the drop down is larger than the text in the menu itself. Also the text in the dropdown feels crushed to me.
Not getting this issue? What breakpoint is this?

3. The people page has a "Meet the team" heading, while the projects, work, and news pages don't. Do we need this? Feels orphaned to me, and I don't think it adds to the page (Who we are and teh down arrow are already strong signage).
This is a different template because it has the team carousel at the top. Not having a header there is more awkward because there is either a gab, or it would be right up against the carousel. I wondered if it could have another paragraph about your culture, but regardless I don't have issue with that header. 

4. The dragonfly data science logo is very small, and I cant really read it. We kind of need that to be clearly legible so people know they are here.
It's very ljkely they know where they are because they clicked on a link with your name on it, or entered the address in the browser. Typically mobile versions only show an icon. If we want people to re-assure they are indeed on the DF site, we could mentioned it in the intro; "Dragonfly is..." either in first or 2nd sentence?

5. On the publications page the grey year box seems too large (I dont get the sense that there is anything else below it)
Yes agreed and I have mentioned this as well. Hopefully an easy fix!

6. On the front page, the heading is "Latest news" but not all the tiles are news. Can we do without this heading. It looks a bit orphaned on the page, and the tiles have there own headings anyway?
It needs the header ("Don't make me think.") but as mentioned above it was meant to only have news items, because we have a whole block linking to the projects now. THis was part of the reason we redesigned the homepage. :-)

**Comment by edwardabraham** [comment]
1. I support removing this link :+1: 
2. It seems to have changed since I last looked at it :scream: (so consider this resolved)
3. It may be that the change in the margin between the heading and the boxes below is making me feel a bit queasy (see also my reaction to the Latest news heading). I think my brain isn't effectively attaching the heading to the boxes below because the left margin in the boxes is a lot less. Anyways, not a biggie. :shrug: 
4. It was the tiny "data science" text, but it looks like this has already been swapped out for the wing-only icon version which is much better. So, yep, resolved. :smile_cat: 
5. :+1:
6. Great. I support making it latest news :smile:

**Comment by edwardabraham** [comment]
@simonwinter a slight wrinkle. The menu headings now enlarge when you are  on a page, for all pages, except for "What we do", e.g., https://uat.dragonfly.co.nz/what-we-do/systems-for-data.html

**Comment by simonwinter** [comment]
Thanks @edwardabraham, saw that one!

**Comment by simonwinter** [comment]
OK @edwardabraham for launch there are a few issues here to consider:

1. The tagging of publications (the by subject filter) is very out of date. They either need manual review, or else, dare I say it, some data science. Maybe the simplest is to remove these for now.
2. Yvan is looking at a better way of finding similar stories so that "You might also like these stories " is more meaningful
3. A custom CSL for the publications would be good. I would remove the "retrieved from" part from this tile (it is a URL inside another URL and looks messy here), put the authors on one line, and the other publication info on a following line (the title and year don't need to be repeated).

I agree with all this. However, I think we can ignore this for go-live & come back to it later?

For the publication tags - I think we could manually update this list (there is a dictionary in the Haskell we need to update too)

On the home page there are 2 pieces of content that require you to make decisions on:

1. Latest news articles - pick your top 4 please!
2. Testimonials - pick your favourites!

If you don't know where they live, please let me know :)

S

**Comment by edwardabraham** [comment]
Yup, these absolutely weren't meant to be blocking issues. Just things that
popped up to me when I was clicking around.

I will go chose four news stories. Hopefully we can automate this at some
point, so the four are literally the four latest.

**Comment by edwardabraham** [comment]
The testimonials that you have at the moment are good for go live.

**Comment by simonwinter** [comment]
Thanks @edwardabraham - I feel that the news thing should be relatively minor at some point ... 🤷 

The last question I have for you is:

> Text truncated ("We're based in Wellington, New") (Zealand is below the fold)

I haven't been able to replicate this. Does this happen if you've used the browser zoom? I feel that's a use-case that ... well the site should mostly work if you zoom in, but I wouldn't expect it to be perfect.

**Comment by edwardabraham** [comment]
Yeah, I would worry about that one!
