### ISSUE TITLE
Dragonfly files

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/dragonfly-website#252]
There is a seperate repo `dragonfly-website-files` which uploads pdfs to a separate bucket. A couple of comments:
* Have a think about the architecture. At the moment, this is being served by Deployhub, could be made into a dependent job?
* There is a 404.html file in here which gets served if the file is missing. This needs to be updated to match the new website https://github.com/dragonfly-science/dragonfly-website-files/blob/master/files/404.html

**Comment by edwardabraham** [comment]
Have set this up as a gorbachev job, which is more visible to us. But can someone have a look at the 404 page, thanks (at the moment it turns up if there is a broken link when specifying a publication file).

**Comment by simonwinter** [comment]
Thanks @edwardabraham - have scheduled to look at this on Wednesday.

**Comment by simonwinter** [comment]
@edwardabraham this has now been updated e.g. https://files.dragonfly.co.nz/publications/pdf/cordwell_research_2022-somenameof-a-file.pdf

It's kinda a dumb process at the moment - literally have to copy the html into that file, update the paths to reference dragonfly.co.nz (rather than relative to /) & commit. It should be more automated than this ... but that's another hill to be climbed in the future.
