### ISSUE TITLE
italics for scientific names in the title of publications

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-website#77]

**Comment by edwardabraham** [comment]
Good point! We have figured out a work around for this. The title that is displayed by default is generated automatically from the citation. This title doesn't have formatting. In order to control the formatting of the title, added a title field to the header of the markdown file. For example, the markdown for [this page](https://www.dragonfly.co.nz/publications/abraham_overlap_2014.html) is below (full file [here](/content/publications/abraham_overlap_2014.md). The italics is specified using the html tags `<i> ... </i>` around the text you want in italics. You can also put unicode in the title field to get any characters you need.

```
---
pdf: AEBR-161-Black-petrel.pdf
tags: edward, yvan, dragonfly, seabird, bycatch, report
title: Overlap of the distribution of black petrel (<i>Procellaria parkinsoni</i>) with New Zealand trawl and longline fisheries
---
Black petrel, *Procellaria parkinsoni*, has been identified as the New Zealand endemic seabird species
that is most at risk from incidental captures in commercial fisheries. The goal of this project was to use
available data to estimate the overlap of New Zealand black petrel with commercial trawl and longline
fisheries.
```

**Comment by katrin-berkenbusch** [comment]
Thanks, that’s cool.

**Comment by katrin-berkenbusch** [comment]
It doesn't seem to work, the scientific name in this title is still roman on the website.

**Comment by edwardabraham** [comment]
It is working, but the website hadn't updated. Fixed now. (@vizowl,
deployhub didn't trigger an update, it was fine when I manually deployed.
Any idea why?)
